blog/urls.py
from django.conf.urls import url,include
from django.views.generic import ListView,DetailView

from blog import views
from blog.models import blog_post


urlpatterns=[
    url(r'^create/$',views.create,name='create'),
    url(r'^view_blog/$',views.view_blog,name='view_blog'),
    url(r'^visit_blog/+(?P<blog_id>\d+)/$',views.visit_blog,name='visit_blog'),
]

coursewebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^joinus/', include('joinus.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^instructor/',include('instructor.urls')),
    url(r'^course/',include('course.urls')),
    url(r'^student/',include('student.urls')),
    url(r'^blog/',include('blog.urls')),
    url(r'^forum/',include('forum.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.UPLOAD_URL, document_root=settings.UPLOAD_ROOT)

instructor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from instructor import views

urlpatterns = [
    url(r'^login/$',views.login,name='instructor_login'),
    url(r'^panel/$',views.instructor_panel,name='instructor_panel'),
    url(r'^createcourse/$',views.create_course,name='create_course'),
    url(r'^managecourse/$',views.managecourse,name='managecourse'),
    url(r'^managecourse/+(?P<course_id>\d+)+/$',views.edit_course,name='editcourse'),
    url(r'^logout/$',views.logout,name='instructor_logout'),
    url(r'^createcourse1/+(?P<course_id>\d+)+/$', views.create_course1, name='createcourse1'),
    url(r'^coursedisplay/+(?P<course_id>\d+)+/$',views.course_display,name='course_display'),
    url(r'^course_lock/+(?P<course_id>\d+)+/$',views.course_lock,name='course_lock'),
    url(r'^course_hide/+(?P<course_id>\d+)+/$',views.course_hide,name='course_hide'),
    url(r'^edit_main_content/+(?P<course_id>\d+)+/$',views.edit_main_content,name='edit_main_content'),
    url(r'^edit_sub_content/+(?P<course_id>\d+)+/$',views.edit_sub_content,name='edit_sub_content'),
    url(r'^delete_sub_content/+(?P<course_id>\d+)+/$',views.delete_sub_content,name='delete_sub_content'),
    url(r'^delete_main_content/+(?P<course_id>\d+)+/$',views.delete_main_content,name='delete_main_content'),
    url(r'^delete_course/+(?P<course_id>\d+)+/$',views.delete_course,name='delete_course'),

    url(r'^resources/+(?P<course_id>\d+)+/$',views.resources,name='resources'),
    url(r'^resource_detail/+(?P<resource_id>\d+)+/$',views.resource_detail,name='resource_detail'),
    url(r'^delete_resource/+(?P<resource_id>\d+)+/$',views.delete_resource,name='delete_resource'),

    url(r'^manage_sequence/+(?P<course_id>\d+)+/$',views.manage_sequence,name='manage_sequence'),
    url(r'^manage_sequence1/+(?P<course_id>\d+)+/$',views.manage_sequence1,name='manage_sequence1'),
    url(r'^move_up/+(?P<course_id>\d+)+/$',views.move_up,name='move_up'),
    url(r'^move_down/+(?P<course_id>\d+)+/$',views.move_down,name='move_down'),
    url(r'^instructor_profile/$',views.instructor_profile,name='instructor_profile'),
    url(r'^edit_profile/$',views.edit_profile,name='edit_profile'),
    url(r'^announcements/$',views.announcement,name='announcements'),
    url(r'^questions_panel/$',views.questions_panel,name='questions_panel'),
    url(r'^view_question/+(?P<question_id>\d+)+/$',views.view_question,name='view_question'),
    url(r'^reply_question/+(?P<question_id>\d+)+/$',views.reply_question,name='reply_question'),
    url(r'^create_questions/$',views.create_questions,name='create_questions'),
    url(r'^question_details/+(?P<question_id>\d+)+/$',views.question_details,name='question_details'),
    url(r'^delete_question/+(?P<question_id>\d+)+/$',views.delete_question,name='delete_question'),

    url(r'^delete_questions/+(?P<course_id>\d+)+/$',views.delete_questions,name='delete_questions'),

    url(r'^question_bank/$',views.question_bank,name='question_bank'),
    url(r'^question_bank1/+(?P<course_id>\d+)+/$',views.question_bank1,name='question_bank1'),
    url(r'^make_quiz/$',views.make_quiz,name='make_quiz'),
    url(r'^make_quiz1/$',views.make_quiz1,name='make_quiz1'),
    url(r'^quiz_display/$',views.quiz_display,name='quiz_display'),
    url(r'^quiz_display1/+(?P<course_id>\d+)+/$',views.quiz_display1,name='quiz_display1'),
    url(r'^quiz_details/+(?P<quiz_id>\d+)+/$',views.quiz_details,name='quiz_details'),
    url(r'^edit_quiz/+(?P<quiz_id>\d+)+/$',views.edit_quiz,name='edit_quiz'),
    url(r'^edit_quiz1/+(?P<quiz_id>\d+)+/$',views.edit_quiz1,name='edit_quiz1'),
    url(r'^delete_quiz/+(?P<quiz_id>\d+)+/$',views.delete_quiz,name='delete_quiz'),
    url(r'^lock_quiz/+(?P<quiz_id>\d+)+/$',views.lock_quiz,name='lock_quiz'),
    url(r'^hide_quiz/+(?P<quiz_id>\d+)+/$',views.hide_quiz,name='hide_quiz'),
    url(r'^earnings/$',views.earnings,name='earnings'),
    url(r'^students_enrolled/+(?P<course_id>\d+)+/$',views.students_enrolled,name='students_enrolled'),
    url(r'^managereview/$', views.managereview, name='managereview'),
    url(r'^approve/+(?P<review_id>\d+)+/$', views.approve, name='approve'),
    url(r'^remove/+(?P<review_id>\d+)+/$', views.remove, name='remove'),
    url(r'^sendmail/+(?P<course_id>\d+)+/$',views.sendmail,name='home'),
    url(r'^upload_csv/+(?P<course_id>\d+)+/$', views.upload_csv, name='upload_csv'),
    url(r'^faq/$', views.faqs, name='faq'),

    url(r'^faq_display/+(?P<course_id>\d+)+/$', views.faq_display, name='faq_display'),
    url(r'^delete_faq/+(?P<faq_id>\d+)+/$', views.delete_faq, name='delete_faq'),
]

instructor/models.py
import datetime
from django.db import models
from joinus.models import student, instructor


# Create your models here.
class categories(models.Model):
    name = models.CharField(max_length = 50)
    def __str__(self):
        return self.name

class course(models.Model):
    cname=models.CharField(max_length=50)
    cdesc=models.CharField(max_length=500,default='none')
    creatorid=models.ForeignKey(instructor,on_delete=models.CASCADE)
    category_id=models.ForeignKey(categories,on_delete=models.CASCADE)
    taughtby=models.CharField(max_length=50)
    prerequisite=models.CharField(max_length=200)
    course_language=models.CharField(max_length=30)
    duration=models.IntegerField()
    fee=models.IntegerField(default=0)
    start_date=models.CharField(max_length=12)
    end_date=models.CharField(max_length=12)
    lock=models.CharField(max_length=1,default=0)
    hide=models.CharField(max_length=1,default=0)
    course_pic=models.FileField(default='abc.jpg')

    def __str__(self):
        return self.cname

class enrolldata(models.Model):
    student_id=models.ForeignKey(student)
    course_id=models.ForeignKey(course)
    join_date=models.CharField(max_length=200,default=str(datetime.datetime.now()))
    fee_status=models.CharField(max_length=1,default='n')
    course_progress=models.CharField(max_length=10,default='0')
    flag=models.CharField(max_length=1,default='0')
    progress_data=models.CharField(max_length=1000,default='')
    def __str__(self):
        return self.course_id.cname+'-'+self.student_id.uname


class coursecontent(models.Model):
    course_id = models.ForeignKey(course,on_delete=models.CASCADE)
    content_sub_id = models.IntegerField(default=0)
    content_name = models.CharField(max_length=50)
    content_description = models.CharField(max_length=500,default='description')
    content_type = models.CharField(default='null',max_length=10)
    content_url = models.FileField(default='abc.mp4')
    content_sequence_no = models.IntegerField(default=-1)
    def __str__(self):
        return self.content_name

class announcements(models.Model):
    course_id = models.ForeignKey(course,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    Adate = models.CharField(max_length=50)
    Atime = models.CharField(max_length=50)
    def __str__ (self):
        return self.title

class resource_type(models.Model):
    name = models.CharField(max_length=10)
    def __str__ (self):
        return self.name

class resources1(models.Model):
    content_id = models.ForeignKey(coursecontent,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    type = models.ForeignKey(resource_type,on_delete=models.CASCADE)
    description = models.CharField(max_length=500,default='none')
    content_url1 = models.FileField(default='xyz.mp4')
    content_url2 = models.CharField(max_length=200,default='')
    sequence_no = models.IntegerField(default=-1)
    def __str__(self):
        return self.name + ":" +self.type.name

class difficulty_levels(models.Model):
    name = models.CharField(max_length=10)
    def __str__ (self):
        return self.name


class add_question(models.Model):
    course_id = models.ForeignKey(course,on_delete=models.CASCADE)
    question = models.CharField(max_length=200)
    question_type = models.CharField(max_length=20)
    answer = models.CharField(max_length=200)
    feedbackc = models.CharField(max_length=200)
    feedbackw = models.CharField(max_length=200)
    hint = models.CharField(max_length=200)
    difficulty = models.ForeignKey(difficulty_levels,on_delete=models.CASCADE)
    option1 = models.CharField(max_length=50,default=None,blank=True,null=True)
    option2 = models.CharField(max_length=50,default=None,blank=True,null=True)
    option3 = models.CharField(max_length=50,default=None,blank=True,null=True)
    option4 = models.CharField(max_length=50,default=None,blank=True,null=True)
    def __str__ (self):
        return self.question

class quiz(models.Model):
    content_id = models.ForeignKey(coursecontent,on_delete=models.CASCADE)
    instructor_id = models.ForeignKey(instructor,on_delete=models.CASCADE)
    question_id = models.CharField(max_length=400)
    quiz_title = models.CharField(max_length=50)
    quiz_description = models.CharField(max_length=500)
    quiz_duration = models.IntegerField()
    quiz_weightage = models.CharField(max_length=4)
    quiz_date = models.CharField(max_length=100)
    difficulty = models.ForeignKey(difficulty_levels,on_delete=models.CASCADE)
    lock = models.CharField(max_length=1)
    hide = models.CharField(max_length=1)
    def __str__ (self):
        return self.quiz_title

class faq(models.Model):
    course_id = models.ForeignKey(course, on_delete=models.CASCADE)
    faq_question = models.CharField(max_length=100)
    faq_answer = models.TextField()

    def __str__(self):
        return self.faq_question

class uploadcsv(models.Model):
    csvfile = models.FileField(default='abc.csv')

instructor/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from instructor.models import add_question, faq
from student.models import askquestion


class add_questionForm(forms.ModelForm):
    question = forms.CharField(widget=SummernoteWidget(attrs={'width': '100%', 'height': '300px','placeholder':'Enter Question Here','required':'required'}))
    class Meta():
        model = add_question
        fields = ['question']
        widgets = {
            #'body': SummernoteInplaceWidget(),
            'question': SummernoteWidget(),
        }

class faq_Form(forms.ModelForm):
    faq_answer = forms.CharField(widget=SummernoteWidget(attrs={'height': '300px','placeholder':'Enter Answer Here',}))
    class Meta():
        model = faq
        fields = ['faq_answer']
        widgets = {
            #'body': SummernoteInplaceWidget(),
            'faq_answer': SummernoteWidget(),
        }

instructor/templates/instructor/faq_display.html
{% extends 'instructor_base.html' %}
{% block head %}
    <title>Question Bank</title>
{% endblock %}
{% block instructorname %}
    {{ instructorname }}
{% endblock %}
{% block logout %}
    <li><a href="/instructor/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
{% endblock %}
{% block signup %}
{% endblock %}
{% block body %}

    <!-- container -->
    <div class="container-fluid text-center animated fadeIn">
        <div class="row content">
            <div class="col-sm-2 sidenav" align="left">
                <div class="well well-sm">
                    <p><a class="btn-link" href="/instructor/panel/"><img src="{{ UPLOAD_URL }}/overview_icon.png"
                                                                          height="25px">Overview</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/managecourse/"><img src="{{ UPLOAD_URL }}/manage_courses.png" height="25px">
                        Manage Courses</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/quiz_display1/{{ course_id }}/"><img src="{{ UPLOAD_URL }}/quiz_icon.png"
                                                                                 height="25px">
                        Quiz's</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/question_bank1/{{ course_id }}/"><img
                            src="{{ UPLOAD_URL }}/question_bank.jpg" height="25px">
                        Question Bank</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/students_enrolled/{{ course_id }}/"><img
                            src="{{ UPLOAD_URL }}/enroll_icon.png" height="25px"> Students Enrolled</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/forum/{{ course_id }}/"><img src="{{ UPLOAD_URL }}/forum.png" height="25px"> Forums</a>
                    </p>
                </div>

            </div>

            <div class="col-sm-10 text-left ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2><img src="{{ UPLOAD_URL }}/question_bank.jpg" height="50px" width="50px"> FAQs
                            <a type="button" href="/instructor/faq/"
                               class="btn btn-primary btn-lg"
                               style="float: right;">Add FAQ
                            </a>
                        </h2>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post"
                              action="/instructor/delete_questions/{{ cname }}/"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <table class="table table-bordered">
                                {% if faqs|length == 0 %}
                                    <tr>
                                        <td colspan="6" align="center">
                                            No FAQs Added Yet
                                        </td>
                                    </tr>
                                {% endif %}
                                <div class="panel-heading">
                                    {% for faq in faqs %}

                                        <tr>
                                            <td width="90%">
                                                <b>Question {{ forloop.counter }}:</b> {{ faq.faq_question }}
                                            </td>
                                            <td width="10%">
                                                <a type="button" href="/instructor/delete_faq/{{ faq.id }}/"
                                                   onclick="return confirm('Are you sure?')">
                                                    <img src="{{ UPLOAD_URL }}/delete.png" height="25px">Delete</a>
                                            </td>
                                        <tr>
                                        <tr>
                                            <td colspan="2">
                                                <b>Answer :</b> {{ faq.faq_answer|safe }}
                                            </td>
                                        </tr>

                                    {% endfor %}
                                </div>
                            </table>
                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <div class="modal fade" id="myModal3" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Make Quiz</h3>
                </div>
                <div class="modal-body">
                    <form method="post" name="form1" action="/instructor/make_quiz/">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="content" style="float:left;">Select Content :</label>
                            <select class="form-control" id="content" name="content">
                                {% for content1 in content %}
                                    <option value="{{ content1.id }}">
                                        {{ content1.content_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="difficulty" style="float:left;">Select Difficulty Level</label>
                            <select class="form-control" id="difficulty" name="difficulty">
                                {% for level in difficulty %}
                                    <option value="{{ level.id }}">
                                        {{ level.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="modal-footer">
                            <!-- <a href="/course/rating_review/{{ course.pk }}/">Already Added Questions</a>-->
                            <button type="submit" class="btn btn-primary" style="margin-left:10px">
                                OK
                            </button>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>

    <div class="modal fade" id="myModal2" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Create Questions</h3>
                </div>
                <div class="modal-body">
                    <form method="post" name="form1" action="/instructor/create_questions/">
                        {% csrf_token %}
                        <input type="hidden" name="from" value="panel">

                        <div class="form-group">
                            <label for="coursename">Select Course :</label>
                            <select class="form-control" id="coursename" name="coursename">
                                {% for course in user1.course_set.all %}
                                    <option value="{{ course.id }}">
                                        {{ course.cname }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="type">&nbsp;Select Question Type</label>

                            <div class="radio">
                                <label><input type="radio" name="type" value="0">Multiple Choice Questions</label>
                            </div>
                            <div class="radio">
                                <label><input type="radio" name="type" value="1">Direct Answer Questions</label>
                            </div>
                            <div class="radio">
                                <label><input type="radio" name="type" value="2">Multiple Correct Options</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary" style="margin-left:10px">
                                Create
                            </button>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>

    <div class="modal fade" id="myModal1" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Upload CSV File</h3>
                </div>
                <div class="modal-body">
                    <form role="form" enctype="multipart/form-data" method="post"
                          action="/instructor/upload_csv/{{ cname }}/">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="hidden" name="coursename" id="coursename" value="{{ cname }}">
                        </div>
                        <div class="form-group">
                            <table class="table table-bordered">
                                <tr>
                                    <td colspan="2">
                                        <label for="content_file">&nbsp;CSV File:</label>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input type="file" class="form-control" id="content_file" name="content_file">
                                    </td>
                                    <td>
                                        <input type="submit" class="form-control" name="Upload" value="Upload"
                                               style="float: right"/>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>
    <!-- container -->
{% endblock %}

instructor/templates/instructor/manage_course.html
{% extends 'instructor_base.html' %}
{% block head %}
    <title>Manage Course</title>
{% endblock %}
{% block instructorname %}
    {{ instructorname }}
{% endblock %}
{% block logout %}
    <li><a href="/instructor/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
{% endblock %}
{% block signup %}
{% endblock %}
{% block body %}

    <!-- container -->
    <div class="container-fluid text-center animated fadeIn">
        <div class="row content">
            <div class="col-sm-2 sidenav" align="left">
                <div class="well well-sm">
                    <p><a class="btn-link" href="/instructor/panel/"><img src="{{ UPLOAD_URL }}/overview_icon.png"
                                                                          height="25px">Overview</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/instructor_profile/"><img src="{{ UPLOAD_URL }}/profile_icon.png" height="25px"> My Profile</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/questions_panel/"><img src="{{ UPLOAD_URL }}/question_icon.png"
                                                                   height="25px"> Direct Questions From Students</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/forum/"><img src="{{ UPLOAD_URL }}/forum.png" height="25px"> Forums</a></p>
                </div>
                <div class="well well-sm">
                    <p><a href="/instructor/earnings/"><img src="{{ UPLOAD_URL }}/earnings.png" height="25px"> Earnings</a>
                    </p>
                </div>
            </div>
            <div class="col-sm-10 text-left ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Welcome {{ user1.fname }} {{ user1.lname }}</h2>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Manage Courses</h2>
                    </div>
                    <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-bordered">
                                {% for coursename in user1.course_set.all %}
                                    <tr>
                                        <td width="60%"><h4>{{ coursename.cname }}</h4></td>
                                        <td width="20%" align="center"><a class="btn btn-primary btn" type="button"
                                                                          href="/instructor/coursedisplay/{{ coursename.pk }}/"
                                                                          class="btn btn-default">Manage</a></td>
                                        <td width="20%" align="center"><a class="btn btn-primary btn" type="button"
                                                                          href="/instructor/createcourse1/{{ coursename.pk }}/"
                                                                          class="btn btn-default">Upload Content</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>

                    </div>
                </div>

            </div>

        </div>
    </div>
    <!-- container -->
{% endblock %}